### SIGN UP Register user 
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "name": "mm",
    "username": "Maxxxx",
    "password": "222"
}

### SIGN IN Get token
POST http://localhost:3000/auth/sign-in 
Content-Type: application/json

{
    "username": "Maxxxx",
    "password": "222"
}

###
POST http://localhost:3000/api/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA0Nzc0NzQsImlhdCI6MTcwMDQzNDI3NCwidXNlcl9pZCI6N30.wb_R3usbp2CKvGXPX7PEjcC24O1b198EBbMcgooNhGg
Content-Type: application/json

{
    "title": "Первая таска"
}

###
GET http://localhost:3000/api/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA0Nzc0NzQsImlhdCI6MTcwMDQzNDI3NCwidXNlcl9pZCI6N30.wb_R3usbp2CKvGXPX7PEjcC24O1b198EBbMcgooNhGg
###
GET http://localhost:3000/api/lists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA0Nzc0NzQsImlhdCI6MTcwMDQzNDI3NCwidXNlcl9pZCI6N30.wb_R3usbp2CKvGXPX7PEjcC24O1b198EBbMcgooNhGg
### 
DELETE http://localhost:3000/api/lists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA0Nzc0NzQsImlhdCI6MTcwMDQzNDI3NCwidXNlcl9pZCI6N30.wb_R3usbp2CKvGXPX7PEjcC24O1b198EBbMcgooNhGg
###
PUT http://localhost:3000/api/lists/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA0Nzc0NzQsImlhdCI6MTcwMDQzNDI3NCwidXNlcl9pZCI6N30.wb_R3usbp2CKvGXPX7PEjcC24O1b198EBbMcgooNhGg
Content-Type: application/json

{
    "title": "Измененная таска",
    "description": "Описание изм"
}