services:
  postgres:
    image: postgres
    container_name: todo-db
    ports:
      - 6500:5432
    env_file:
      - ./configs/config.yml
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
